### ISSUE TITLE
El nombre de la etiqueta h2 “Todas las solicitudes” está incorrecto:

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#10]
**Problema actual:**

La etiqueta h2 “Todas las solicitudes” en el módulo de “Gestión de roles” es incorrecto, ya que en este contexto no hay usuarios que necesiten ser validados o aceptados. 

**Sugerencia de Mejora:**

En su lugar, se debe cambiar el contenido de la etiqueta h2 por “Todos los usuarios”.

**Gravedad / impacto**

Gravedad Baja
 
**Evidencia**

![image](https://github.com/user-attachments/assets/4dddaab2-fd2b-490b-bd2c-8c758d6b4035)

@luisleon98  @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se modificó el texto de la etiqueta h2 

![image](https://github.com/user-attachments/assets/238d3e72-5c96-4cc1-9412-a3c187fb8888)

**Comment by 3c1enfuegos** [comment]
¡Amigo, el cambio realizado es perfecto! Este issue queda solventado. ¡Buen trabajo! 🎉

¡Muchas Gracias!
