### ISSUE TITLE
Los iconos de guardar/ cancelar son poco claros

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#11]
**Problema actual:**

Los iconos para guardar o cancelar en la ventana emergente de datos del usuario carecen de tooltip, lo que los hace poco claros.

**Sugerencia de mejora:**

Se propone que se implementen etiquetas o tooltips en los iconos mencionados para mejorar la claridad y usabilidad.

**Gravedad / impacto**

Sugerencia de mejora 

**Evidencia**

![image](https://github.com/user-attachments/assets/0d74c9b9-69f8-4b52-adab-f1e70d999e73)

@luisleon98  @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se implementa tooltip con las leyendas "Guardar" y "Cancelar"



![image](https://github.com/user-attachments/assets/eb99c9bb-438d-4343-ab29-95e00c89c7f6)

![image](https://github.com/user-attachments/assets/21fecfa5-aacc-45e4-b36c-fd088c99962f)

**Comment by 3c1enfuegos** [comment]
¡Los cambios realizados son correctos! Este issue queda solventado, espero a que se suba para revisarlo. Te agradezco @Gerardo-Soto-dsi19 

¡Buen trabajo! 🎉
