### ISSUE TITLE
Validación de Credenciales:

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#12]
**Problema actual:**

El sistema no proporciona información sobre si la validación de las credenciales es correcta o incorrecta. 

**Sugerencia de mejora:**

_Verificación Inicial:_
Si alguno de los campos está vacío, mostrar un mensaje de error: "Por favor, asegúrate de ingresar tu correo electrónico y contraseña correctamente." 

_Autenticación:_
Si no coinciden, mostrar un mensaje de error: “Las credenciales proporcionadas no son válidas. Por favor, verifica tu nombre de usuario y contraseña e inténtalo de nuevo.”

_Intentos Fallidos:_
Después de un número determinado de intentos fallidos (por ejemplo, 5), bloquear la cuenta temporalmente y mostrar un mensaje: "Demasiados intentos fallidos. Tu cuenta ha sido bloqueada temporalmente. Por favor, intenta de nuevo más tarde"

**Gravedad / impacto**

Sugerencia de mejora

**Evidencia**

https://github.com/user-attachments/assets/62bf0ffd-8bee-4932-9be4-bbd9dc62e857

@luisleon98 
@Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos el comportamiento de no mostrar el error cuando no se ingresan credenciales o credenciales incorrectas se debe a la  funcionalidad hot module replacement (HMR) de Vite que es la parte del servidor del front del proyecto local.  Vite lanza una actualización de la página, a pesar de que se ha implementado el manejo de errores, sin embargo, el comportamiento en producción es diferente, ya que se despliega en un servidor Nginx y ahí no se presenta ese comportamiento.

Evidencia del comportamiento en prod 

https://github.com/user-attachments/assets/2da44cde-a7fa-4a5c-a026-29e6132d3fa7

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos  Se realizan mejoras en la validación de credenciales y se implementa la funcionalidad de _Intentos Fallidos_

https://github.com/user-attachments/assets/cf5869da-80af-4a7d-bf74-d127d5ef978a

**Comment by 3c1enfuegos** [comment]
Buen día, Gerardo, las mejoras implementadas cubren y cumplen satisfactoriamente con lo solicitado, se procede con el cierre del este issue
