### ISSUE TITLE
En la pantalla de Recuperar Contraseña, la etiqueta "Ingrese el usuario" es incorrecta

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#13]
**Problema actual:**

La etiqueta “Ingrese el usuario” es incorrecta, ya que en todo momento nos referimos al correo electrónico como el identificador del usuario. Esto puede resultar confuso para los usuarios.

**Sugerencia de mejora:**

Se recomienda utilizar la etiqueta “Ingrese su correo electrónico” en lugar de “Ingrese el usuario”, ya que esto sería más preciso y menos confuso para los usuarios. Además, se podría mejorar añadiendo un placeholder en el campo de entrada (input).

**Gravedad / impacto**

Sugerencia de mejora 

**Evidencia**

![image](https://github.com/user-attachments/assets/c3a94734-6d08-485d-8998-db36779a2e1a)

@luisleon98  @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos  Se modifica la etiqueta reemplazando "Ingrese el usuario” por "Ingrese su correo electrónico"

![Image](https://github.com/user-attachments/assets/4f029e05-eb63-4b07-9cbc-d2593a1c7b9c)

**Comment by 3c1enfuegos** [comment]
Buen día,  las mejoras cubren y cumplen satisfactoriamente con lo solicitado, se procede con el cierre del este issue
