### ISSUE TITLE
La validación para restablecer la contraseña carece de información cuando el correo electrónico no es válido.

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#14]
**Problema actual:**

Como se puede observar en el video adjunto, al hacer clic en el botón de recuperar con un correo no registrado, solo aparece una ventana de error sin proporcionar más detalles sobre el problema.

**Sugerencia de mejora:**

Es necesario mostrar mensajes de error claros y específicos si el correo electrónico no es válido. Por ejemplo: “El correo electrónico ingresado no está registrado. Por favor, ingrese un correo electrónico válido.” Además, se debe implementar una validación que verifique el formato del correo electrónico antes de enviar la solicitud de restablecimiento de contraseña.

**Gravedad / impacto**

Sugerencia de mejora 

**Evidencia**

https://github.com/user-attachments/assets/d2881cac-5329-4f1d-8b3e-8db852a88e32

@luisleon98 
@Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se implementa el mensaje de error y la validación del correo ingresado en el input

![image](https://github.com/user-attachments/assets/2d3c2085-b2dd-4b2b-b88f-6d135d9a3197)


![image](https://github.com/user-attachments/assets/bd6cf57b-07e3-46ed-bafb-fda9f6d0f5c2)

**Comment by 3c1enfuegos** [comment]
¡Amigo, los cambios realizados son correctos! Este issue queda solventado. Espero a que se suba para revisarlo.
¡Buen trabajo! 🎉
