### ISSUE TITLE
Mejora para el texto de la venta de restablecimiento de contraseña.

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#15]
**Sugerencia de mejora:**

Sí, la sintaxis del texto de esta ventana es correcta. Sin embargo, podrías considerar una pequeña mejora para mayor claridad:

“Le hemos enviado un correo electrónico para restablecer su contraseña.”

**Gravedad / impacto**

Sugerencia de mejora 

**Evidencia**
_Ejemplo del cambio aplicado._

![popRestablecePass](https://github.com/user-attachments/assets/bfb08133-7171-47ed-8b46-51a76c28893f)

@luisleon98  @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se aplica la sugerencia para el mensaje de alerta 

![image](https://github.com/user-attachments/assets/d374d537-0142-4714-95e7-22d6a142d102)

**Comment by 3c1enfuegos** [comment]
¡El cambio realizado es correcto! Este issue queda solventado, espero a que se suba para revisarlo. Te agradezco @Gerardo-Soto-dsi19 
¡Buen trabajo! 🎉
