### ISSUE TITLE
Agregar el signo de admiración faltante 

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#16]
**Sugerencia de mejora:**

Agregar el signo de admiración de apertura que falta en el texto: ¡Regístrate aquí!

**Gravedad / impacto**

Sugerencia de mejora 

**Evidencia**

![image](https://github.com/user-attachments/assets/1bea4b84-3d98-44e9-850b-a9690bb175ad)

@luisleon98  @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se agrega el signo faltante 

![image](https://github.com/user-attachments/assets/05204c3a-ec51-4d66-8eb9-7cafe93eded1)
