### ISSUE TITLE
Corrige la ortografía en la pantalla de Gestión de roles 

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#17]
**Sugerencia de mejora:**

Corrige la ortografía en la página del "Gestor de roles" y el Pop Up "Datos del usuario"

_Pantalla: Gestión de roles_

- Corregir “Gestor de publicaiones” por “Gestor de publicaciones”.
- Corregir “Administrador de sistema” por “Administrador del sistema”.

_Pop Up: Datos del usuario_

- Corregir “Pueblos Mágicos” por “Pueblos mágicos”.

**Gravedad / impacto**

Sugerencia de mejora 

**Evidencia**

![Gestor](https://github.com/user-attachments/assets/73c6dcc3-a0ea-4059-add4-a094e2250fc2)

**Comment by Gerardo-Soto-dsi19** [comment]
Se corrige la ortografía 

![image](https://github.com/user-attachments/assets/c920f3ac-91e6-4a5d-945c-d0135c5eccb6)

**Comment by 3c1enfuegos** [comment]
¡Los cambios realizados son correctos! Este issue queda solventado. Espero a que se suba para revisarlo. Te agradezco @Gerardo-Soto-dsi19 

¡Buen trabajo! 🎉
