### ISSUE TITLE
Cambio del nombre en la etiqueta estado en las solicitudes pendientes 

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#18]
**Resultado esperado:**

Como sugerencia de mejora y con el fin de homologar los nombres, y dado que todas las etiquetas del tipo de solicitud tienen una similitud con el estatus, solicito que se cambie la etiqueta del estado “en validación” por “pendiente”, tal como se llama el tipo de solicitud, para mantener coherencia y relación entre ellas.

**Gravedad:**

Sugerencia de Mejora 

**Evidencia:**

![image](https://github.com/user-attachments/assets/d1f784a9-78b8-4f05-8242-701a81683a59)

@Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos se modifica la etiqueta del side bar 

![image](https://github.com/user-attachments/assets/4f444358-5eb7-45fd-94f0-c57d042748ac)

**Comment by 3c1enfuegos** [comment]
Se han realizado los cambios de manera correcta, así que se procede a cerrar el issue.
