### ISSUE TITLE
Pantalla Error de Aplicación en Opción Editar Perfil

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#7]
- **Problema actual:**

Registré un nuevo usuario y luego fui a la opción de “Editar perfil”. De repente, mientras estaba en la pantalla de edición del perfil, apareció un error. Intenté replicar el problema, pero hasta ahora solo ha ocurrido en dos ocasiones. Al recargar la página, la pantalla de edición del perfil se abre normalmente.

- **Clasificación/Impacto:**

Si el error persiste, podría afectar la funcionalidad de este módulo y volverse un issue bloqueante 

- **Evidencia**

![image](https://github.com/user-attachments/assets/14d11bb0-716e-46dd-b74f-ddd07f4432f7)

@luisleon98 @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos hasta el momento no he podido replicar el error, realicé 20 altas de usuario y no presento ningún problema, las pruebas las hice en 2 exploradores diferentes (Edge y Chrome)

https://github.com/user-attachments/assets/09c4b4c7-7704-44c0-91f7-d45ba88fff88
