### ISSUE TITLE
Los nombres de los roles no se encuentran homologados en el gestor de roles

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#8]
**- Problema actual:**

Los Roles no se encuentran homologados y estandarizado para todo el módulo de Gestor de roles 

**- Propuesta o sugerencia:**

Revisar y corregir los nombres de los roles en los elementos “Tipo de usuario” y en la lista desplegable “Rol” de la ventana “datos de usuario”, asegurando que todos correspondan correctamente con los roles asignados en el módulo de Gestión de roles. 

Roles:

1. Administrador del Sistema
2. Director de Pueblos Mágicos
3. Representante de Pueblo Mágico

**- Impacto/gravedad:**

Gravedad Media 

**- Evidencia:**

https://github.com/user-attachments/assets/afbd937f-f14b-4bac-9a67-a185f495527a

@ @luisleon98  @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se homologan los nombres para mostrar en el front.

![Image](https://github.com/user-attachments/assets/26e04cf0-9699-4cc5-b3b1-8b6d841bf98a)


![Image](https://github.com/user-attachments/assets/bc7d2fa3-d492-4388-812f-c41e34034b7b)

**Comment by 3c1enfuegos** [comment]
Amigo, te comentó que, según los roles establecidos en la guía del usuario, los cambios que realizaste no solventan el issue. Los roles correctos son:

- Administrador del Sistema
- Director de Pueblos Mágicos
- Representante de Pueblo Mágico

Por favor, ¿puedes ajustarlos en el sistema conforme a estos nombres para resolver el issue? ¡Gracias!

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos Se modifican los nombres de los roles según lo solicitado

![Image](https://github.com/user-attachments/assets/7a63d015-66a3-44d3-9a48-be9a4673de45)

**Comment by 3c1enfuegos** [comment]
Hola Gerardo,

He visto los cambios y están muy bien, solo hay un par de cosas que ajustar:

- Cambia la “s” minúscula, por una “S” mayúscula en el título del rol de la parte superior.
- Me equivoqué en el nombre de uno de los roles. Debería ser “Representante del Pueblo Mágico”. ¿Me ayudas con esa corrección?

Gracias.

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos se modifican las etiquetas con base en el comentario anterior 

![Image](https://github.com/user-attachments/assets/c35bb73c-a89e-438d-89d0-651b60688b8a)

**Comment by 3c1enfuegos** [comment]
Buenos días, perfecto, muchas gracias por el apoyo. issue solventado se procede a cerrarlo.
