### ISSUE TITLE
Agregar los campos “Tipo de usuario” y "Pueblo" en el mismo de registro de nuevos usuarios del (admin):

### ISSUE THREAD

**Issue by 3c1enfuegos** [Gerardo-Soto-dsi19/Pueblos-Magicos#9]
**Problema actual:**

Para asignar el tipo de rol y el pueblo al cual pertenece un usuario, primero se debe registrar al nuevo usuario. Luego, desde el Gestor de roles, selecciona “Todos los usuarios”, elige al nuevo usuario, haz clic en las opciones y luego en “Editar” para asignar estos datos. Este proceso puede resultar un poco engorroso.

**Sugerencia de Mejora:**

- Desde el Rol de Administrador de sistemas o Director de Pueblos:

Para mejorar la UI/UX del usuario al registrar un nuevo usuario desde el módulo “Gestor de roles”, proponemos agregar los siguientes campos en la misma plantilla de registro:

1. Seleccionar el tipo de rol del nuevo usuario 
(Directivo de Pueblos Mágicos, Representante de Pueblo Mágico o turista).
2. Seleccionar el pueblo al que pertenece o representa.

**Gravedad/ Impacto**

Sugerencia de mejora / Usabilidad

**Evidencia**

![image](https://github.com/user-attachments/assets/413eba21-9832-4930-bcde-a49db98df020)

@luisleon98 @Gerardo-Soto-dsi19

**Comment by Gerardo-Soto-dsi19** [comment]
Se implementa la mejora para poder seleccionar el rol del usuario a dar de alta.

El rol de turista no se da de alta dentro del gestor, ya que ese rol es exclusivo de la aplicación móvil. 

![Image](https://github.com/user-attachments/assets/c878fa9d-bd33-456c-b932-0ae226885f8a)

**Comment by 3c1enfuegos** [comment]
El cambio realizado me gusta. Además de la mejora que ya implementaste, falta agregar el combo de “Pueblo”. Según lo mencionado con Brayan, cada usuario registrado debe contar con el pueblo del cual es originario o al que representa, especialmente en el caso de los “Representantes de Pueblo Mágico”.  

¿Podrías por favor ajustar estos cambios en el formulario? ¡Gracias, amigo!

**Comment by Gerardo-Soto-dsi19** [comment]
En este caso habría que tocar base con Brayan, ya que no todos los usuarios deben tener asignado un pueblo mágico (específicamente el administrador y el director de pueblo mágico).
 Si no mal recuerdo en la reunión solo se acordó asignar el rol desde esta pantalla 🤔

**Comment by 3c1enfuegos** [comment]
@Gerardo-Soto-dsi19 Si, lo platicamos con él para que todos estemos en la misma sintonía, pero si hice hincapié en el cambio de estos dos elementos en la pantalla de Registrar nuevo usuario, para que no sea necesario dar de alta al usuario y luego tener que editarlo para agregar los elementos faltantes (rol y pueblo).

**Comment by Gerardo-Soto-dsi19** [comment]
@3c1enfuegos se realiza la implementación de un select para asignar el pueblo mágico desde la pantalla

![Image](https://github.com/user-attachments/assets/4be0d680-22d1-4f68-8573-1e47e484c98a)

**Comment by 3c1enfuegos** [comment]
Gerardo, te agradezco todo tu apoyo, los cambios se ven muy bien. Queda solventado este issue.
